In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from os import listdir
from os.path import join

import matplotlib.style as style
style.use('fivethirtyeight')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

### Goal: create data set for Bayesian modeling of win probability based on team kills, deaths, and assists

In [28]:
team_data = pd.read_csv('../data/team_matches_master.csv')
print(team_data.shape)
team_data.head()

(128680, 9)


map_id  map           date  team_id team_name  team_score  team_kills  \
0   12838  NaN  1347562800000     4411       NiP          16        91.0   
1   12839  NaN  1347562800000     4411       NiP          16        83.0   
2   12840  NaN  1347562800000     4444    Blight          16        81.0   
3   12841  NaN  1347562800000     4444    Blight          16        97.0   
4   12848  NaN  1348401600000     4411       NiP          16       102.0   

   team_deaths  team_assists  
0         46.0           0.0  
1         34.0           0.0  
2         37.0           0.0  
3         58.0           0.0  
4         86.0           0.0

In [41]:
# Drop rows where team assists is zero
team_data = team_data[team_data['team_assists'] != 0]
print(team_data.shape)

# Drop rows where NaN in team_kills
team_data = team_data[~team_data['team_kills'].isna()]
print(team_data.shape)

# Collect maps where match went to overtime and drop
drop_maps = team_data.loc[team_data['team_score'] > 16, 'map_id'].values
team_data = team_data[~team_data['map_id'].isin(drop_maps)]
print(team_data.shape)

# Create dependent feature
team_data['won'] = 0
team_data.loc[team_data['team_score'] == 16, 'won'] = 1
team_data = team_data.reset_index()
team_data.head()

(117442, 10)
(117442, 10)
(117442, 10)


index  map_id  map           date  team_id    team_name  team_score  \
0    233   13417  NaN  1353348000000     4411          NiP          16   
1    234   13419  NaN  1353438329000     4411          NiP          16   
2    235   13420  NaN  1353574800000     4411          NiP          16   
3    236   13421  NaN  1353574800000     4465  mousesports          16   
4    237   13422  NaN  1353582000000     4411          NiP          16   

   team_kills  team_deaths  team_assists  won  
0        82.0         42.0          19.0    1  
1        89.0         65.0          24.0    1  
2        88.0         55.0          16.0    1  
3        89.0         60.0          18.0    1  
4        98.0        104.0          21.0    1

In [108]:
# Write out dataset for bayesian analysis
bayes_set = team_data[['team_kills', 'team_assists', 'won']].sample(1000, random_state=42)

In [109]:
bayes_set['team_kills'].values

array([ 96.,  31.,  50.,  96.,  82.,  92., 100.,  82.,  96.,  87., 112.,
        88.,  98.,  76.,  81.,  82., 101.,  94., 106., 106.,  85.,  99.,
       102.,  55., 100.,  81.,  59.,  86.,  81.,  84.,  83.,  97.,  94.,
       105.,  87.,  78.,  37., 104.,  92.,  80.,  83., 107.,  39.,  83.,
        98.,  88., 100.,  88.,  45.,  90.,  74.,  89.,  73., 101.,  76.,
        89.,  49.,  72.,  89., 106., 104.,  92.,  92.,  78.,  94., 110.,
        99.,  98., 105.,  99.,  81., 101., 109.,  46.,  93., 100.,  83.,
        90.,  54.,  98.,  79., 101., 103.,  68.,  96.,  82.,  54.,  85.,
        77.,  72.,  33., 106.,  90.,  91.,  84.,  87., 102.,  85., 104.,
       102.,  87.,  99.,  97., 102.,  81.,  58., 108.,  65., 108., 102.,
       101.,  89.,  64.,  89.,  42.,  95.,  70.,  97.,  83.,  82.,  99.,
        49.,  84.,  66.,  82., 108.,  34.,  96.,  90.,  57., 112.,  73.,
       101.,  94.,  93., 109.,  98.,  81.,  86.,  87., 112.,  95.,  93.,
       108.,  84., 100.,  59.,  37.,  70.,  69.,  9

In [110]:
bayes_set['team_assists'].values

array([20.,  4.,  6., 18., 26., 23., 26., 26., 16., 24., 22., 15., 20.,
       14., 16., 16., 13., 13., 26., 20., 18., 18., 18.,  6., 18.,  6.,
       12., 12., 21., 21., 18., 12., 19., 24., 22., 16.,  5., 32., 13.,
       16., 14., 20., 10., 11., 24., 16., 17.,  9., 11., 16., 15., 21.,
       18., 17., 13., 21., 10., 15., 22., 21., 25., 14., 17.,  6., 14.,
       12., 17., 13., 20., 17.,  9., 18., 20.,  3., 19., 14., 12., 20.,
       13., 13., 10., 23., 18., 15., 18., 17.,  7., 20., 13., 19.,  7.,
       25., 21., 19., 13., 16., 29., 11., 21., 19., 17., 20., 24., 14.,
       20., 14., 20., 15., 17., 21., 20., 17., 18., 22.,  6., 15., 12.,
       18., 18., 16., 16.,  5., 12.,  9., 15., 28.,  8., 13., 17.,  8.,
       27., 18., 14., 18., 19., 22., 20., 18., 13., 23., 21., 17., 17.,
       27., 18., 17., 10.,  6., 16., 13., 27., 10., 18., 17., 11., 21.,
       17., 17., 22.,  7., 14., 18., 15.,  8.,  8., 11., 17., 17., 21.,
       19., 10., 12., 23., 29., 17.,  7., 16., 14., 14., 15., 12

In [111]:
bayes_set['won'].values

array([1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,

In [113]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

train_x = team_data[['team_kills', 'team_assists']].sample(10000, random_state=42)
train_y = team_data['won'].sample(10000, random_state=42)

clf = RandomForestClassifier(random_state=42)
clf2 = LogisticRegression()
clf.fit(train_x, train_y)
clf2.fit(train_x, train_y)

/Users/jad/miniconda3/envs/ml/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/jad/miniconda3/envs/ml/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [125]:
test = [
    [101, 19],
    [105, 31],
    [89, 27]
]

In [126]:
clf.predict_proba(test)

array([[0.29157437, 0.70842563],
       [0.27511905, 0.72488095],
       [0.        , 1.        ]])

In [127]:
clf2.predict_proba(test)

array([[0.16119896, 0.83880104],
       [0.1354065 , 0.8645935 ],
       [0.48362853, 0.51637147]])

In [119]:
print('Logistic Regression Params:')
print(clf2.intercept_)
print(clf2.coef_)

Logistic Regression Params:
[-9.77814406]
[[ 0.11729006 -0.02204302]]


In [121]:
team_data[(team_data['team_kills'] > team_data['team_deaths']) & (team_data['won'] == 0)]

index  map_id      map           date  team_id  \
9          242   13427      NaN  1353594600000     4613   
25         258   13443      NaN  1353682500000     4429   
26         259   13444      NaN  1353682500000     4413   
56         289   13474      NaN  1354212900000     4548   
61         294   13479      NaN  1354356000000     4548   
106        339   13525      NaN  1355421600000     4490   
203        442   13643      NaN  1358877600000     4547   
238        477   13679      NaN  1359914400000     4494   
279        520   13725      NaN  1360782900000     4683   
345        588   13803      NaN  1361390400000     4467   
363        607   13824      NaN  1361615400000     4467   
465        711   13943      NaN  1362510000000     4687   
586        836   14086      NaN  1363802400000     4532   
703        995   14250      NaN  1364560200000     4647   
743       1036   14313      NaN  1364598900000     4679   
809       1105   14385      NaN  1364922000000     4851   
837       1133   14422      NaN  1364585400000     4807   
882       1179   14469      NaN  1365247800000     4623   
892       1189   14479      NaN  1365321600000     4445   
920       1221   14515      NaN  1365960600000     4775   
959       1266   14586      cch  1366556400000     4467   
995       1306   14631      NaN  1368558000000     4467   
1014      1325   14652      NaN  1368993600000     4548   
1039      1352   14688      NaN  1369253700000     4548   
1090      1408   14753      NaN  1369936800000     4609   
1096      1414   14760      NaN  1370192400000     4555   
1102      1420   14766      NaN  1370200500000     4558   
1151      1474   14826      NaN  1370887200000     4532   
1187      1512   14869      NaN  1371142800000     4674   
1244      1573   14935      NaN  1372017304000     4532   
1331      1664   15034      NaN  1373790600000     4978   
1394      1729   15105      NaN  1376589600000     4744   
1412      1748   15126      NaN  1376788500000     4624   
1438      1776   15163      NaN  1377705600000     4608   
1494      1836   15232      NaN  1378490400000     4467   
1497      1839   15235      NaN  1378497600000     4467   
1509      1852   15249      NaN  1378659600000     4467   
1562      1907   15313      NaN  1378953900000     5007   
1568      1913   15320      NaN  1379043000000     5095   
1687      2044   15488      NaN  1380157200000     4624   
1691      2048   15492      NaN  1380214800000     4984   
1698      2055   15499      NaN  1380223800000     4608   
1766      2127   15577      NaN  1380910800000     5106   
1800      2165   15620      NaN  1381431600000     5144   
1801      2166   15621      NaN  1381435200000     4411   
1851      2218   15676      NaN  1382637600000     5140   
1871      2242   15727     nuke  1383325200000     4948   
1962      2335   15875      mrg  1386098100000     5028   
2000      2376   15944       d2  1386356400000     4608   
2068      2449   16055      inf  1381770000000     4694   
2169      2562   16194      inf  1387710900000     5273   
2186      2580   16216      NaN  1390081500000     5091   
2192      2586   16222     nuke  1390099500000     5005   
2266      2667   16313      inf  1392841800000     4448   
2274      2677   16326     nuke  1393272000000     4991   
2300      2707   16360      trn  1393447200000     4494   
2353      2767   16431      inf  1394132400000     4991   
2357      2771   16435     nuke  1394136000000     4948   
2391      2808   16478      inf  1394654400000     4469   
2415      2833   16505       d2  1394819700000     4411   
2503      2930   16618     nuke  1396378800000     5211   
2521      2949   16638      mrg  1396814400000     5378   
2522      2950   16639      trn  1396882800000     4991   
2690      3149   16988        -  1401639300000     5422   
2696      3155   16994        -  1401650400000     5422   
2750      3210   17053      inf  1402905600000     4413   
2849      3312   17164       d2  1404147600000     5641 